<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uule.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Protocol.Uule</code>
 */
class Uule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 role = 1;</code>
     */
    protected $role = null;
    /**
     * Generated from protobuf field <code>int32 producer = 2;</code>
     */
    protected $producer = null;
    /**
     * Generated from protobuf field <code>string canonicalName = 4;</code>
     */
    protected $canonicalName = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $role
     *     @type int $producer
     *     @type string $canonicalName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Uule::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 role = 1;</code>
     * @return int
     */
    public function getRole()
    {
        return isset($this->role) ? $this->role : 0;
    }

    public function hasRole()
    {
        return isset($this->role);
    }

    public function clearRole()
    {
        unset($this->role);
    }

    /**
     * Generated from protobuf field <code>int32 role = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkInt32($var);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 producer = 2;</code>
     * @return int
     */
    public function getProducer()
    {
        return isset($this->producer) ? $this->producer : 0;
    }

    public function hasProducer()
    {
        return isset($this->producer);
    }

    public function clearProducer()
    {
        unset($this->producer);
    }

    /**
     * Generated from protobuf field <code>int32 producer = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setProducer($var)
    {
        GPBUtil::checkInt32($var);
        $this->producer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string canonicalName = 4;</code>
     * @return string
     */
    public function getCanonicalName()
    {
        return isset($this->canonicalName) ? $this->canonicalName : '';
    }

    public function hasCanonicalName()
    {
        return isset($this->canonicalName);
    }

    public function clearCanonicalName()
    {
        unset($this->canonicalName);
    }

    /**
     * Generated from protobuf field <code>string canonicalName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCanonicalName($var)
    {
        GPBUtil::checkString($var, True);
        $this->canonicalName = $var;

        return $this;
    }

}

